### ISSUE TITLE
The latest version is crashing on startup

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1056]
**Describe the bug**
The latest version from the master branch seem to crash on startup.

**To Reproduce**
1. Build the master branch.
2. Launch it.

**Expected behavior**
App should start properly.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Insider Preview
 - App version: v0.10.2

**Additional context**

`2020-06-13 18:51:13.7994|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.View_Models.SettingsViewModel.LoadTerminalApps()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)`

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran I have not been able to reproduce using the steps you mentioned. Can you try cleaning or maybe even re-clone the solution and test again?

**Comment by gave92** [comment]
@Jaiganeshkumaran I was having the same issue. I fixed it by changing the Build Action for the file "Files\Assets\terminal\terminal.json" from "None" to "Content" in my local branch. I don't know why I have to do it and other people don't.

**Comment by Jaiganeshkumaran** [comment]
I'm closing this issue since it's working for me now.
