### ISSUE TITLE
Files UWP Dev doesn't work on Windows 10 Version 1903

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1306]
**Describe the bug**
The latest version of the app from GitHub doesn't run on my Windows 10 PC with 1903.

**Expected behavior**
App should work on 1903 since the minimum version is 1809.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 18362.175
 - App version: v0.11.0 (Latest master branch)

**Additional context**
`2020-06-30 12:53:58.3359|ERROR|Files.App|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Windows.UI.Xaml.Markup.XamlParseException: XAML parsing failed.
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Files.Views.Pages.ModernShellPage.InitializeComponent()
   at Files.Views.Pages.ModernShellPage..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateIn|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Windows.UI.Xaml.Markup.XamlParseException: XAML parsing failed.
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Files.Views.Pages.ModernShellPage.InitializeComponent()
   at Files.Views.Pages.ModernShellPage..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Microsoft.UI.Xaml.Markup.XamlReflectionType.ActivateInstance()
   at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter)
   at Files.InstanceTabsView.<>c__DisplayClass12_0.<AddNewTab>b__1(Object <p0>, RoutedEventArgs <p1>)
`

**Comment by Samboy-Chips** [comment]
I think this confirms #1293

**Comment by Jaiganeshkumaran** [comment]
> I think this confirms #1293

However, Files UWP Preview works fine for me. I'm in the Files UWP insider preview.

**Comment by Jaiganeshkumaran** [comment]
Both works on my Insider machine (20152.1000)

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Is this still an issue with v0.13.1?

**Comment by jaigak** [comment]
@yair100 Actually I found out that this is an SDK issue. Building against 2004 on 1903 doesn't work properly and this even occurs when building other projects.
